# Copyright (C) 2026. Huawei Technologies Co., Ltd. All rights reserved.

"""Stable ScienceAgent construction API backed by one typed builder."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, Any, Callable, Sequence

from scienceflow.agent.core.ports.callback_ports import AgentCallbackPorts
from scienceflow.agent.core.runtime.run_policy import RunPolicy
from scienceflow.research.state.knowledge.skills.catalog.registry import SkillRegistry

if TYPE_CHECKING:
    from scienceflow.interfaces.ui.console import RichUI

from scienceflow.agent.factory.construction.builder import (
    AgentConstructionOptions,
    ScienceAgentBuilder,
)


def __init__(
    self,
    *,
    workspace_dir: str | Path = ".",
    sandbox: bool = True,
    ui: RichUI | None = None,
    max_steps: int | None = None,
    exec_feedback_max_chars: int = 5000,
    scienceflow_stdout_max_chars: int = 0,
    sliding_window_budget_chars: int = 60_000,
    pinned_budget_ratio: float = 0.45,
    sliding_window_priority_enabled: bool = True,
    mid_run_compact_enabled: bool = False,
    llm_stream_timeout_sec: int = 1800,
    llm_tool_stream_max_attempts: int = 5,
    llm_tool_stream_retry_base_delay_sec: float = 1.75,
    llm_tool_stream_retry_max_delay_sec: float = 20.0,
    stream_repetition_detection: bool = True,
    stream_repetition_window_chars: int = 4000,
    stream_repetition_ngram_len: int = 150,
    stream_repetition_max_repeats: int = 3,
    stream_max_output_chars_soft: int = 30000,
    stream_repetition_retry_max: int = 2,
    bash_timeout_sec: float = 1800.0,
    bash_timeout_slow_sec: float = 1800.0,
    bash_max_output_chars: int = 8000,
    bash_max_stream_line_chars: int = 2400,
    bash_observation_summary_enabled: bool = False,
    system_prompt_hook: Callable[[str], str] | None = None,
    system_prompt_core: str | None = None,
    path_guard_extra_roots: Sequence[str | Path] | None = None,
    extra_env: dict[str, str] | None = None,
    readonly_dirs: Sequence[str] | None = None,
    run_policy: RunPolicy | None = None,
    embedded_full_run_enabled: bool = False,
    skip_embedded_duplicate_when_progressive_bare_success: bool = True,
    embedded_full_run_update_result_md: bool = True,
    embedded_full_run_timeout_sec: float | None = None,
    fullrun_output_tail_stdout_lines: int = 50,
    fullrun_output_tail_stderr_lines: int = 0,
    fullrun_output_tail_max_chars: int = 4000,
    quick_test_extrapolation_enabled: bool = True,
    quick_test_extrapolation_budget_sec: float | None = None,
    quick_test_extrapolation_rows: int = 20,
    fullrun_epoch_watchdog_enabled: bool = True,
    fullrun_epoch_watchdog_budget_sec: float | None = None,
    interaction_log_level: str = "normal",
    interaction_log_full: bool = False,
    interaction_log_color: bool = True,
    interaction_log_llm_stream: bool = False,
    interaction_log_layout: str = "flat",
    bash_stream_to_interaction_log: bool = True,
    bash_output_dedup_enabled: bool = True,
    bash_output_dedup_min_repeat: int = 3,
    bash_output_dedup_summary_prefix: str = "[log-dedup]",
    bash_output_dedup_apply_to_memory: bool = True,
    tool_memory_compression: bool = True,
    include_write_edit_tools: bool = True,
    tool_display_paths_relative: bool = True,
    tool_display_root: str | Path | None = None,
    write_return_full_max_chars: int = 12000,
    write_return_full_max_lines: int = 250,
    write_return_head_tail_lines: int = 40,
    edit_return_full_max_chars: int = 12000,
    edit_return_full_max_lines: int = 250,
    edit_return_head_tail_lines: int = 40,
    edit_return_change_ctx_lines: int = 8,
    edit_failure_top_k_candidates: int = 3,
    edit_failure_diag_max_chars: int = 2000,
    file_snapshot_latest_only: bool = True,
    grep_max_results_lines: int = 50,
    bash_success_tail_lines: int = 20,
    bash_success_tail_lines_solution: int = 8,
    bash_success_tail_lines_test: int = 120,
    bash_success_tail_lines_readonly: int = 30,
    bash_success_tail_lines_install: int = 5,
    read_success_max_lines: int = 200,
    write_auto_snapshot_enabled: bool = True,
    write_auto_snapshot_paths: Sequence[str] | None = None,
    write_auto_snapshot_code_extensions: Sequence[str] | None = None,
    write_auto_snapshot_max_lines: int = 400,
    write_auto_snapshot_max_chars: int = 8_000,
    write_auto_snapshot_changed_context_lines: int = 10,
    write_auto_snapshot_symbol_body_lines: int = 3,
    read_overlap_guard_enabled: bool = True,
    msg0_compress_body: bool = False,
    on_llm_call: Callable[[dict[str, Any]], None] | None = None,
    debug_dynamic_steps_enabled: bool = False,
    debug_step_boost: int = 0,
    debug_max_steps_cap: int = 0,
    round_budget_prompt_cap: int = 0,
    parallel_bash_enabled: bool = True,
    parallel_llm_tool_calls: bool = True,
    lnr_explore_streak_inject_after: int = 0,
    lnr_single_read_streak_inject_after: int = 0,
    no_progress_hard_stop_after: int = 0,
    no_progress_hardstop_guard_grace_rounds: int = 1,
    repeated_runtime_error_threshold: int = 2,
    rotating_runtime_error_threshold: int = 3,
    rotating_distinct_types_min: int = 2,
    no_success_run_soft_threshold: int = 6,
    no_success_run_hard_threshold: int = 12,
    edit_short_old_str_chars: int = 40,
    lnr_category_skill_text: str = "",
    lnr_phase_skill_registry: dict[str, str] | None = None,
    lnr_phase_skill_descriptions: dict[str, str] | None = None,
    lnr_skill_inject_max_chars: int = 12000,
    lnr_periodic_no_solution_every: int = 0,
    lnr_llm_turns_log_enabled: bool = False,
    lnr_llm_turns_log_path: str | Path | None = None,
    sft_data_log_path: str | Path | None = None,
    mlebench_validate_after_embedded_full_run: bool = False,
    mlebench_data_dir: str | None = None,
    mlebench_exp_id: str | None = None,
    lnr_mlebench_validate_enabled: bool = True,
    lnr_run_control_max_fix_rounds: int = 5,
    # LNR only: end ``run()`` after a bare solution run passes run-control checks.
    lnr_stop_after_bare_solution_success: bool = False,
    lnr_superloop_enabled: bool = False,
    # Teleport mode (search-wide system prompt + 4-class fork policy). When != "off",
    # the per-agent ``_lnr_phase_header`` is suppressed (kept empty) so guard/periodic
    # nudge messages do not re-inject ``## Phase Header`` blocks into chat — the
    # search-wide system prompt already conveys phase-agnostic rules.
    teleport_mode: str = "off",
    # REPL/code-agent mode: keep the system prompt byte-stable by omitting
    # dynamic file-state and round-budget suffixes. Dynamic state remains in
    # tool results and workspace files instead of the system prefix.
    stable_system_prompt: bool = False,
    workspace_git_auto_checkpoint_enabled: bool = False,
    workspace_git_track_globs: Sequence[str] | None = None,
    search_round_offset: int = 0,
    skill_registry: SkillRegistry | None = None,
    task_type: str | None = None,
    skill_allow_names: Sequence[str] | None = None,
    skill_tool_mode: str = "all",
    skill_allow_generic_wildcard: bool = True,
    skill_visible_max: int = 0,
    resource_observer: Any | None = None,
    interaction_log_session: str | None = None,
    interaction_log_phase: str | None = None,
    lnr_exploit_ensemble_mode: bool = False,
    lnr_hide_future_stages: bool = False,
    callback_ports: AgentCallbackPorts | None = None,
    **kwargs: Any,
) -> None:
    ScienceAgentBuilder(
        self,
        AgentConstructionOptions(
            workspace_dir=workspace_dir,
            sandbox=sandbox,
            ui=ui,
            max_steps=max_steps,
            exec_feedback_max_chars=exec_feedback_max_chars,
            scienceflow_stdout_max_chars=scienceflow_stdout_max_chars,
            sliding_window_budget_chars=sliding_window_budget_chars,
            pinned_budget_ratio=pinned_budget_ratio,
            sliding_window_priority_enabled=sliding_window_priority_enabled,
            mid_run_compact_enabled=mid_run_compact_enabled,
            llm_stream_timeout_sec=llm_stream_timeout_sec,
            llm_tool_stream_max_attempts=llm_tool_stream_max_attempts,
            llm_tool_stream_retry_base_delay_sec=llm_tool_stream_retry_base_delay_sec,
            llm_tool_stream_retry_max_delay_sec=llm_tool_stream_retry_max_delay_sec,
            stream_repetition_detection=stream_repetition_detection,
            stream_repetition_window_chars=stream_repetition_window_chars,
            stream_repetition_ngram_len=stream_repetition_ngram_len,
            stream_repetition_max_repeats=stream_repetition_max_repeats,
            stream_max_output_chars_soft=stream_max_output_chars_soft,
            stream_repetition_retry_max=stream_repetition_retry_max,
            bash_timeout_sec=bash_timeout_sec,
            bash_timeout_slow_sec=bash_timeout_slow_sec,
            bash_max_output_chars=bash_max_output_chars,
            bash_max_stream_line_chars=bash_max_stream_line_chars,
            bash_observation_summary_enabled=bash_observation_summary_enabled,
            system_prompt_hook=system_prompt_hook,
            system_prompt_core=system_prompt_core,
            path_guard_extra_roots=path_guard_extra_roots,
            extra_env=extra_env,
            readonly_dirs=readonly_dirs,
            run_policy=run_policy,
            embedded_full_run_enabled=embedded_full_run_enabled,
            skip_embedded_duplicate_when_progressive_bare_success=(
                skip_embedded_duplicate_when_progressive_bare_success
            ),
            embedded_full_run_update_result_md=embedded_full_run_update_result_md,
            embedded_full_run_timeout_sec=embedded_full_run_timeout_sec,
            fullrun_output_tail_stdout_lines=fullrun_output_tail_stdout_lines,
            fullrun_output_tail_stderr_lines=fullrun_output_tail_stderr_lines,
            fullrun_output_tail_max_chars=fullrun_output_tail_max_chars,
            quick_test_extrapolation_enabled=quick_test_extrapolation_enabled,
            quick_test_extrapolation_budget_sec=quick_test_extrapolation_budget_sec,
            quick_test_extrapolation_rows=quick_test_extrapolation_rows,
            fullrun_epoch_watchdog_enabled=fullrun_epoch_watchdog_enabled,
            fullrun_epoch_watchdog_budget_sec=fullrun_epoch_watchdog_budget_sec,
            interaction_log_level=interaction_log_level,
            interaction_log_full=interaction_log_full,
            interaction_log_color=interaction_log_color,
            interaction_log_llm_stream=interaction_log_llm_stream,
            interaction_log_layout=interaction_log_layout,
            bash_stream_to_interaction_log=bash_stream_to_interaction_log,
            bash_output_dedup_enabled=bash_output_dedup_enabled,
            bash_output_dedup_min_repeat=bash_output_dedup_min_repeat,
            bash_output_dedup_summary_prefix=bash_output_dedup_summary_prefix,
            bash_output_dedup_apply_to_memory=bash_output_dedup_apply_to_memory,
            tool_memory_compression=tool_memory_compression,
            include_write_edit_tools=include_write_edit_tools,
            tool_display_paths_relative=tool_display_paths_relative,
            tool_display_root=tool_display_root,
            write_return_full_max_chars=write_return_full_max_chars,
            write_return_full_max_lines=write_return_full_max_lines,
            write_return_head_tail_lines=write_return_head_tail_lines,
            edit_return_full_max_chars=edit_return_full_max_chars,
            edit_return_full_max_lines=edit_return_full_max_lines,
            edit_return_head_tail_lines=edit_return_head_tail_lines,
            edit_return_change_ctx_lines=edit_return_change_ctx_lines,
            edit_failure_top_k_candidates=edit_failure_top_k_candidates,
            edit_failure_diag_max_chars=edit_failure_diag_max_chars,
            file_snapshot_latest_only=file_snapshot_latest_only,
            grep_max_results_lines=grep_max_results_lines,
            bash_success_tail_lines=bash_success_tail_lines,
            bash_success_tail_lines_solution=bash_success_tail_lines_solution,
            bash_success_tail_lines_test=bash_success_tail_lines_test,
            bash_success_tail_lines_readonly=bash_success_tail_lines_readonly,
            bash_success_tail_lines_install=bash_success_tail_lines_install,
            read_success_max_lines=read_success_max_lines,
            write_auto_snapshot_enabled=write_auto_snapshot_enabled,
            write_auto_snapshot_paths=write_auto_snapshot_paths,
            write_auto_snapshot_code_extensions=write_auto_snapshot_code_extensions,
            write_auto_snapshot_max_lines=write_auto_snapshot_max_lines,
            write_auto_snapshot_max_chars=write_auto_snapshot_max_chars,
            write_auto_snapshot_changed_context_lines=(
                write_auto_snapshot_changed_context_lines
            ),
            write_auto_snapshot_symbol_body_lines=write_auto_snapshot_symbol_body_lines,
            read_overlap_guard_enabled=read_overlap_guard_enabled,
            msg0_compress_body=msg0_compress_body,
            on_llm_call=on_llm_call,
            debug_dynamic_steps_enabled=debug_dynamic_steps_enabled,
            debug_step_boost=debug_step_boost,
            debug_max_steps_cap=debug_max_steps_cap,
            round_budget_prompt_cap=round_budget_prompt_cap,
            parallel_bash_enabled=parallel_bash_enabled,
            parallel_llm_tool_calls=parallel_llm_tool_calls,
            lnr_explore_streak_inject_after=lnr_explore_streak_inject_after,
            lnr_single_read_streak_inject_after=lnr_single_read_streak_inject_after,
            no_progress_hard_stop_after=no_progress_hard_stop_after,
            no_progress_hardstop_guard_grace_rounds=(
                no_progress_hardstop_guard_grace_rounds
            ),
            repeated_runtime_error_threshold=repeated_runtime_error_threshold,
            rotating_runtime_error_threshold=rotating_runtime_error_threshold,
            rotating_distinct_types_min=rotating_distinct_types_min,
            no_success_run_soft_threshold=no_success_run_soft_threshold,
            no_success_run_hard_threshold=no_success_run_hard_threshold,
            edit_short_old_str_chars=edit_short_old_str_chars,
            lnr_category_skill_text=lnr_category_skill_text,
            lnr_phase_skill_registry=lnr_phase_skill_registry,
            lnr_phase_skill_descriptions=lnr_phase_skill_descriptions,
            lnr_skill_inject_max_chars=lnr_skill_inject_max_chars,
            lnr_periodic_no_solution_every=lnr_periodic_no_solution_every,
            lnr_llm_turns_log_enabled=lnr_llm_turns_log_enabled,
            lnr_llm_turns_log_path=lnr_llm_turns_log_path,
            sft_data_log_path=sft_data_log_path,
            mlebench_validate_after_embedded_full_run=(
                mlebench_validate_after_embedded_full_run
            ),
            mlebench_data_dir=mlebench_data_dir,
            mlebench_exp_id=mlebench_exp_id,
            lnr_mlebench_validate_enabled=lnr_mlebench_validate_enabled,
            lnr_run_control_max_fix_rounds=lnr_run_control_max_fix_rounds,
            lnr_stop_after_bare_solution_success=lnr_stop_after_bare_solution_success,
            lnr_superloop_enabled=lnr_superloop_enabled,
            teleport_mode=teleport_mode,
            stable_system_prompt=stable_system_prompt,
            workspace_git_auto_checkpoint_enabled=(
                workspace_git_auto_checkpoint_enabled
            ),
            workspace_git_track_globs=workspace_git_track_globs,
            search_round_offset=search_round_offset,
            skill_registry=skill_registry,
            task_type=task_type,
            skill_allow_names=skill_allow_names,
            skill_tool_mode=skill_tool_mode,
            skill_allow_generic_wildcard=skill_allow_generic_wildcard,
            skill_visible_max=skill_visible_max,
            resource_observer=resource_observer,
            interaction_log_session=interaction_log_session,
            interaction_log_phase=interaction_log_phase,
            lnr_exploit_ensemble_mode=lnr_exploit_ensemble_mode,
            lnr_hide_future_stages=lnr_hide_future_stages,
            callback_ports=callback_ports,
            model_fields=kwargs,
        ),
    ).build()


def configure_callback_ports(
    self,
    ports: AgentCallbackPorts | None = None,
    **updates: Any,
) -> None:
    """Install narrow callback capabilities at a stable composition boundary."""

    effective = ports or self.callback_ports
    self.callback_ports = effective.with_overrides(**updates) if updates else effective
