// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App holds the desktop application state: the shared context and the
 * configured gateway base URL. All agent interaction (invoke + transcript)
 * flows through the log gateway; there is no backend chat bridge anymore.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DownloadZip proxies the workspace download-zip endpoint and returns the
 * resulting archive as base64.
 */
export function DownloadZip(paths: string[], taskRoot: string, token: string): $CancellablePromise<$models.FilePayload> {
    return $Call.ByID(923006072, paths, taskRoot, token).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GatewayActivateModel(token: string, modelID: string, sessionID: string): $CancellablePromise<$models.GatewayModelInfo> {
    return $Call.ByID(301239561, token, modelID, sessionID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GatewayActivateSession activates (switches to) an existing session, refreshing
 * its TTL and returning the unified session view.
 */
export function GatewayActivateSession(token: string, sessionID: string): $CancellablePromise<$models.GatewaySession> {
    return $Call.ByID(1317463800, token, sessionID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GatewayAgentStatus queries the current agent task status and output.
 */
export function GatewayAgentStatus(token: string, sessionID: string): $CancellablePromise<$models.GatewayAgentStatus> {
    return $Call.ByID(3577568644, token, sessionID).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GatewayCreateModel(token: string, req: $models.GatewayModelCreateRequest): $CancellablePromise<$models.GatewayModelInfo> {
    return $Call.ByID(1497389798, token, req).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GatewayCreateSession creates a subscription session for the token's user.
 */
export function GatewayCreateSession(token: string, sources: string[]): $CancellablePromise<$models.GatewaySession> {
    return $Call.ByID(2909320531, token, sources).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GatewayDeleteModel(token: string, modelID: string): $CancellablePromise<void> {
    return $Call.ByID(3843579683, token, modelID);
}

/**
 * GatewayDeleteSession removes a session.
 */
export function GatewayDeleteSession(token: string, sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(4067723466, token, sessionID);
}

/**
 * GatewayFetchFiles fetches the current workspace file tree for a session via
 * GET /sessions/{id}/files. Used for on-demand full-tree calibration (e.g.
 * after an overflow event).
 */
export function GatewayFetchFiles(token: string, sessionID: string): $CancellablePromise<$models.FileTreeResponse> {
    return $Call.ByID(3807480550, token, sessionID).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GatewayFetchMonitor(token: string, sessionID: string): $CancellablePromise<$models.GatewayMonitorMetrics> {
    return $Call.ByID(4205294799, token, sessionID).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GatewayGetModelStages(token: string, sessionID: string): $CancellablePromise<$models.GatewayModelStages> {
    return $Call.ByID(2721198247, token, sessionID).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GatewayGetSession queries a session.
 */
export function GatewayGetSession(token: string, sessionID: string): $CancellablePromise<$models.GatewaySession> {
    return $Call.ByID(2777198301, token, sessionID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GatewayInvokeAgent triggers a ScienceFlow agent task on the session.
 */
export function GatewayInvokeAgent(token: string, sessionID: string, req: $models.GatewayInvokeRequest): $CancellablePromise<$models.GatewayTaskSnapshot> {
    return $Call.ByID(2345587090, token, sessionID, req).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GatewayListModels(token: string): $CancellablePromise<$models.GatewayModelInfo[]> {
    return $Call.ByID(129917091, token).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * GatewayListSessions lists all live sessions owned by the token's user.
 */
export function GatewayListSessions(token: string): $CancellablePromise<$models.GatewaySessionsResponse> {
    return $Call.ByID(2222036260, token).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * GatewayListSources returns the sources visible to the token's user.
 */
export function GatewayListSources(token: string): $CancellablePromise<$models.GatewaySourceInfo[]> {
    return $Call.ByID(1805186297, token).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * GatewayLogin authenticates against the log gateway and returns the token and
 * the sources visible to the user.
 */
export function GatewayLogin(req: $models.GatewayLoginRequest): $CancellablePromise<$models.GatewayLoginResult> {
    return $Call.ByID(2197308054, req).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * GatewayReadSnapshot fetches cached file content by path or by source name.
 * Only one of path/source should be set.
 */
export function GatewayReadSnapshot(token: string, path: string, source: string): $CancellablePromise<$models.GatewaySnapshot> {
    return $Call.ByID(2013493121, token, path, source).then(($result: any) => {
        return $$createType13($result);
    });
}

export function GatewaySetModelStages(token: string, sessionID: string, coderModelID: string, feedbackModelID: string): $CancellablePromise<$models.GatewayModelStages> {
    return $Call.ByID(3215920819, token, sessionID, coderModelID, feedbackModelID).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GatewayStartStream (re)starts the log gateway SSE stream for a session.
 */
export function GatewayStartStream(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(2031154011, sessionID);
}

/**
 * GatewayStopAgent kills the current agent task for the session.
 */
export function GatewayStopAgent(token: string, sessionID: string): $CancellablePromise<$models.GatewayTaskSnapshot> {
    return $Call.ByID(3887270490, token, sessionID).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GatewayStopStream stops the current log gateway SSE stream.
 */
export function GatewayStopStream(): $CancellablePromise<void> {
    return $Call.ByID(2328425305);
}

/**
 * GatewayTestConnection probes the gateway server itself (GET /healthz, no
 * token required) and reports reachability plus round-trip latency.
 */
export function GatewayTestConnection(): $CancellablePromise<$models.GatewayHealth> {
    return $Call.ByID(2015285173).then(($result: any) => {
        return $$createType14($result);
    });
}

export function GatewayUpdateModel(token: string, modelID: string, req: $models.GatewayModelUpdateRequest): $CancellablePromise<$models.GatewayModelInfo> {
    return $Call.ByID(2297112557, token, modelID, req).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GatewayUpdateSessionSources replaces a session's subscriptions (full replace).
 */
export function GatewayUpdateSessionSources(token: string, sessionID: string, sources: string[]): $CancellablePromise<$models.GatewaySession> {
    return $Call.ByID(1657044062, token, sessionID, sources).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetGatewayURL returns the currently configured log gateway base URL.
 */
export function GetGatewayURL(): $CancellablePromise<string> {
    return $Call.ByID(2002454112);
}

/**
 * GetSystemStats returns live resource usage of the local machine. Non-Windows
 * platforms return zeroed values (the desktop build targets Windows).
 */
export function GetSystemStats(): $CancellablePromise<$models.SystemStats> {
    return $Call.ByID(549671605).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * ListThemeBackgrounds returns the Agent Map background images available in
 * <program dir>/themes/backgrounds. The option label equals the file name.
 */
export function ListThemeBackgrounds(): $CancellablePromise<string[]> {
    return $Call.ByID(338949167).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * Proxy forwards an arbitrary HTTP request to the log gateway and returns the
 * raw response body. It is used for all JSON/text endpoints (the gateway
 * reverse-proxies /api/* to the ScienceFlow backend when needed).
 */
export function Proxy(req: $models.ProxyRequest): $CancellablePromise<$models.ProxyResponse> {
    return $Call.ByID(1217497507, req).then(($result: any) => {
        return $$createType17($result);
    });
}

/**
 * ReadThemeBackground returns one background image as a data URI so the
 * webview can render files that live outside the bundled frontend assets.
 * An empty string signals an unknown, unreadable or oversized image.
 */
export function ReadThemeBackground(name: string): $CancellablePromise<string> {
    return $Call.ByID(3801301898, name);
}

/**
 * SetGatewayURL changes the log gateway base URL at runtime.
 */
export function SetGatewayURL(url: string): $CancellablePromise<void> {
    return $Call.ByID(452498604, url);
}

/**
 * UploadDataset uploads a single dataset file (multipart field "file").
 */
export function UploadDataset(file: $models.UploadedFile, sessionID: string, token: string): $CancellablePromise<$models.UploadResult> {
    return $Call.ByID(3159165124, file, sessionID, token).then(($result: any) => {
        return $$createType18($result);
    });
}

/**
 * UploadDatasetFolder uploads multiple dataset files (multipart field "files").
 */
export function UploadDatasetFolder(files: $models.UploadedFile[], sessionID: string, token: string): $CancellablePromise<$models.UploadResult> {
    return $Call.ByID(404851632, files, sessionID, token).then(($result: any) => {
        return $$createType18($result);
    });
}

/**
 * WorkspaceDownload downloads a single file or a directory (as zip) from the
 * gateway. If isDir is true, uses /api/workspace/directory/download; otherwise
 * /api/workspace/file/download. The response is base64-encoded binary.
 */
export function WorkspaceDownload(token: string, sessionID: string, path: string, isDir: boolean): $CancellablePromise<$models.FilePayload> {
    return $Call.ByID(852292342, token, sessionID, path, isDir).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * WorkspaceUploadFiles uploads one or more files to a target directory in the
 * workspace via multipart form-data. targetDir is a workspace-root-relative
 * path (empty = root). Files' Filename may contain sub-path separators.
 */
export function WorkspaceUploadFiles(token: string, sessionID: string, targetDir: string, files: $models.UploadedFile[]): $CancellablePromise<$models.WorkspaceUploadResult> {
    return $Call.ByID(1118024202, token, sessionID, targetDir, files).then(($result: any) => {
        return $$createType19($result);
    });
}

/**
 * WorkspaceUploadZip uploads a zip archive and extracts it to a target directory.
 * The zipData is base64-encoded. targetDir is a workspace-root-relative path.
 */
export function WorkspaceUploadZip(token: string, sessionID: string, targetDir: string, zipData: string): $CancellablePromise<$models.WorkspaceDirUploadResult> {
    return $Call.ByID(525216978, token, sessionID, targetDir, zipData).then(($result: any) => {
        return $$createType20($result);
    });
}

// Private type creation functions
const $$createType0 = $models.FilePayload.createFrom;
const $$createType1 = $models.GatewayModelInfo.createFrom;
const $$createType2 = $models.GatewaySession.createFrom;
const $$createType3 = $models.GatewayAgentStatus.createFrom;
const $$createType4 = $models.FileTreeResponse.createFrom;
const $$createType5 = $models.GatewayMonitorMetrics.createFrom;
const $$createType6 = $models.GatewayModelStages.createFrom;
const $$createType7 = $models.GatewayTaskSnapshot.createFrom;
const $$createType8 = $Create.Array($$createType1);
const $$createType9 = $models.GatewaySessionsResponse.createFrom;
const $$createType10 = $models.GatewaySourceInfo.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $models.GatewayLoginResult.createFrom;
const $$createType13 = $models.GatewaySnapshot.createFrom;
const $$createType14 = $models.GatewayHealth.createFrom;
const $$createType15 = $models.SystemStats.createFrom;
const $$createType16 = $Create.Array($Create.Any);
const $$createType17 = $models.ProxyResponse.createFrom;
const $$createType18 = $models.UploadResult.createFrom;
const $$createType19 = $models.WorkspaceUploadResult.createFrom;
const $$createType20 = $models.WorkspaceDirUploadResult.createFrom;
