// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * FilePayload carries a binary download back to the frontend as base64.
 */
export class FilePayload {
    "filename": string;
    "contentType": string;
    "data": string;

    /** Creates a new FilePayload instance. */
    constructor($$source: Partial<FilePayload> = {}) {
        if (!("filename" in $$source)) {
            this["filename"] = "";
        }
        if (!("contentType" in $$source)) {
            this["contentType"] = "";
        }
        if (!("data" in $$source)) {
            this["data"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FilePayload instance from a string or object.
     */
    static createFrom($$source: any = {}): FilePayload {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FilePayload($$parsedSource as Partial<FilePayload>);
    }
}

/**
 * FileTreeNode mirrors the gateway's file tree node (flat list, relative paths).
 */
export class FileTreeNode {
    "name": string;
    "path": string;
    "type": string;
    "size": number;
    "mtime": number;

    /** Creates a new FileTreeNode instance. */
    constructor($$source: Partial<FileTreeNode> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("mtime" in $$source)) {
            this["mtime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileTreeNode instance from a string or object.
     */
    static createFrom($$source: any = {}): FileTreeNode {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileTreeNode($$parsedSource as Partial<FileTreeNode>);
    }
}

/**
 * FileTreeResponse mirrors GET /sessions/{id}/files.
 */
export class FileTreeResponse {
    "root": string;
    "tree": FileTreeNode[];

    /** Creates a new FileTreeResponse instance. */
    constructor($$source: Partial<FileTreeResponse> = {}) {
        if (!("root" in $$source)) {
            this["root"] = "";
        }
        if (!("tree" in $$source)) {
            this["tree"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileTreeResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): FileTreeResponse {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tree" in $$parsedSource) {
            $$parsedSource["tree"] = $$createField1_0($$parsedSource["tree"]);
        }
        return new FileTreeResponse($$parsedSource as Partial<FileTreeResponse>);
    }
}

/**
 * GatewayAgentStatus mirrors GET /sessions/{id}/agent.
 */
export class GatewayAgentStatus {
    "task"?: GatewayTaskSnapshot | null;
    "output"?: string;
    "running"?: boolean;
    "queue_stats"?: GatewayQueueStats | null;

    /**
     * "idle" when no task
     */
    "status"?: string;

    /** Creates a new GatewayAgentStatus instance. */
    constructor($$source: Partial<GatewayAgentStatus> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GatewayAgentStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): GatewayAgentStatus {
        const $$createField0_0 = $$createType3;
        const $$createField3_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("task" in $$parsedSource) {
            $$parsedSource["task"] = $$createField0_0($$parsedSource["task"]);
        }
        if ("queue_stats" in $$parsedSource) {
            $$parsedSource["queue_stats"] = $$createField3_0($$parsedSource["queue_stats"]);
        }
        return new GatewayAgentStatus($$parsedSource as Partial<GatewayAgentStatus>);
    }
}

/**
 * GatewayHealth reports the result of probing the gateway's GET /healthz.
 */
export class GatewayHealth {
    "status": string;
    "subscribers": number;
    "url": string;
    "latency_ms": number;

    /** Creates a new GatewayHealth instance. */
    constructor($$source: Partial<GatewayHealth> = {}) {
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("subscribers" in $$source)) {
            this["subscribers"] = 0;
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("latency_ms" in $$source)) {
            this["latency_ms"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GatewayHealth instance from a string or object.
     */
    static createFrom($$source: any = {}): GatewayHealth {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GatewayHealth($$parsedSource as Partial<GatewayHealth>);
    }
}

/**
 * GatewayInvokeRequest is the POST /sessions/{id}/invoke body.
 */
export class GatewayInvokeRequest {
    "query": string;

    /**
     * "lite" | "heavy"
     */
    "mode"?: string;

    /** Creates a new GatewayInvokeRequest instance. */
    constructor($$source: Partial<GatewayInvokeRequest> = {}) {
        if (!("query" in $$source)) {
            this["query"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GatewayInvokeRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): GatewayInvokeRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GatewayInvokeRequest($$parsedSource as Partial<GatewayInvokeRequest>);
    }
}

/**
 * GatewayLoginRequest is the POST /login body.
 */
export class GatewayLoginRequest {
    "user_name": string;
    "password": string;

    /** Creates a new GatewayLoginRequest instance. */
    constructor($$source: Partial<GatewayLoginRequest> = {}) {
        if (!("user_name" in $$source)) {
            this["user_name"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GatewayLoginRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): GatewayLoginRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GatewayLoginRequest($$parsedSource as Partial<GatewayLoginRequest>);
    }
}

/**
 * GatewayLoginResult is the POST /login response.
 */
export class GatewayLoginResult {
    "token": string;
    "expires_at": string;
    "user": string;
    "sources": string[];

    /** Creates a new GatewayLoginResult instance. */
    constructor($$source: Partial<GatewayLoginResult> = {}) {
        if (!("token" in $$source)) {
            this["token"] = "";
        }
        if (!("expires_at" in $$source)) {
            this["expires_at"] = "";
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("sources" in $$source)) {
            this["sources"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GatewayLoginResult instance from a string or object.
     */
    static createFrom($$source: any = {}): GatewayLoginResult {
        const $$createField3_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sources" in $$parsedSource) {
            $$parsedSource["sources"] = $$createField3_0($$parsedSource["sources"]);
        }
        return new GatewayLoginResult($$parsedSource as Partial<GatewayLoginResult>);
    }
}

export class GatewayModelCreateRequest {
    "model_name": string;
    "api_key": string;
    "api_url": string;

    /** Creates a new GatewayModelCreateRequest instance. */
    constructor($$source: Partial<GatewayModelCreateRequest> = {}) {
        if (!("model_name" in $$source)) {
            this["model_name"] = "";
        }
        if (!("api_key" in $$source)) {
            this["api_key"] = "";
        }
        if (!("api_url" in $$source)) {
            this["api_url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GatewayModelCreateRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): GatewayModelCreateRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GatewayModelCreateRequest($$parsedSource as Partial<GatewayModelCreateRequest>);
    }
}

export class GatewayModelInfo {
    "id": string;
    "model_name": string;
    "api_key": string;
    "api_key_masked": string;
    "api_url": string;
    "is_active": boolean;
    "created_at"?: string;
    "updated_at"?: string;

    /** Creates a new GatewayModelInfo instance. */
    constructor($$source: Partial<GatewayModelInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("model_name" in $$source)) {
            this["model_name"] = "";
        }
        if (!("api_key" in $$source)) {
            this["api_key"] = "";
        }
        if (!("api_key_masked" in $$source)) {
            this["api_key_masked"] = "";
        }
        if (!("api_url" in $$source)) {
            this["api_url"] = "";
        }
        if (!("is_active" in $$source)) {
            this["is_active"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GatewayModelInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): GatewayModelInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GatewayModelInfo($$parsedSource as Partial<GatewayModelInfo>);
    }
}

export class GatewayModelStages {
    "coder_model_id": string;
    "feedback_model_id": string;

    /** Creates a new GatewayModelStages instance. */
    constructor($$source: Partial<GatewayModelStages> = {}) {
        if (!("coder_model_id" in $$source)) {
            this["coder_model_id"] = "";
        }
        if (!("feedback_model_id" in $$source)) {
            this["feedback_model_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GatewayModelStages instance from a string or object.
     */
    static createFrom($$source: any = {}): GatewayModelStages {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GatewayModelStages($$parsedSource as Partial<GatewayModelStages>);
    }
}

export class GatewayModelUpdateRequest {
    "model_name": string;
    "api_key": string;
    "api_url": string;

    /** Creates a new GatewayModelUpdateRequest instance. */
    constructor($$source: Partial<GatewayModelUpdateRequest> = {}) {
        if (!("model_name" in $$source)) {
            this["model_name"] = "";
        }
        if (!("api_key" in $$source)) {
            this["api_key"] = "";
        }
        if (!("api_url" in $$source)) {
            this["api_url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GatewayModelUpdateRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): GatewayModelUpdateRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GatewayModelUpdateRequest($$parsedSource as Partial<GatewayModelUpdateRequest>);
    }
}

export class GatewayMonitorMetrics {
    "session_id": string;
    "workspace": string;
    "updated_at": string;
    "sources": string[];
    "resources": GatewayMonitorResource;
    "tokens": GatewayMonitorTokens;
    "runtime": GatewayMonitorRuntime;

    /** Creates a new GatewayMonitorMetrics instance. */
    constructor($$source: Partial<GatewayMonitorMetrics> = {}) {
        if (!("session_id" in $$source)) {
            this["session_id"] = "";
        }
        if (!("workspace" in $$source)) {
            this["workspace"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }
        if (!("sources" in $$source)) {
            this["sources"] = [];
        }
        if (!("resources" in $$source)) {
            this["resources"] = (new GatewayMonitorResource());
        }
        if (!("tokens" in $$source)) {
            this["tokens"] = (new GatewayMonitorTokens());
        }
        if (!("runtime" in $$source)) {
            this["runtime"] = (new GatewayMonitorRuntime());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GatewayMonitorMetrics instance from a string or object.
     */
    static createFrom($$source: any = {}): GatewayMonitorMetrics {
        const $$createField3_0 = $$createType6;
        const $$createField4_0 = $$createType7;
        const $$createField5_0 = $$createType8;
        const $$createField6_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sources" in $$parsedSource) {
            $$parsedSource["sources"] = $$createField3_0($$parsedSource["sources"]);
        }
        if ("resources" in $$parsedSource) {
            $$parsedSource["resources"] = $$createField4_0($$parsedSource["resources"]);
        }
        if ("tokens" in $$parsedSource) {
            $$parsedSource["tokens"] = $$createField5_0($$parsedSource["tokens"]);
        }
        if ("runtime" in $$parsedSource) {
            $$parsedSource["runtime"] = $$createField6_0($$parsedSource["runtime"]);
        }
        return new GatewayMonitorMetrics($$parsedSource as Partial<GatewayMonitorMetrics>);
    }
}

export class GatewayMonitorResource {
    "cpu_percent": number;
    "memory_percent": number;
    "memory_used_gb": number;
    "storage_bytes": number;
    "storage_files": number;
    "storage_display": string;

    /** Creates a new GatewayMonitorResource instance. */
    constructor($$source: Partial<GatewayMonitorResource> = {}) {
        if (!("cpu_percent" in $$source)) {
            this["cpu_percent"] = 0;
        }
        if (!("memory_percent" in $$source)) {
            this["memory_percent"] = 0;
        }
        if (!("memory_used_gb" in $$source)) {
            this["memory_used_gb"] = 0;
        }
        if (!("storage_bytes" in $$source)) {
            this["storage_bytes"] = 0;
        }
        if (!("storage_files" in $$source)) {
            this["storage_files"] = 0;
        }
        if (!("storage_display" in $$source)) {
            this["storage_display"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GatewayMonitorResource instance from a string or object.
     */
    static createFrom($$source: any = {}): GatewayMonitorResource {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GatewayMonitorResource($$parsedSource as Partial<GatewayMonitorResource>);
    }
}

export class GatewayMonitorRuntime {
    "status": string;
    "elapsed": string;
    "elapsed_ms": number;

    /** Creates a new GatewayMonitorRuntime instance. */
    constructor($$source: Partial<GatewayMonitorRuntime> = {}) {
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("elapsed" in $$source)) {
            this["elapsed"] = "";
        }
        if (!("elapsed_ms" in $$source)) {
            this["elapsed_ms"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GatewayMonitorRuntime instance from a string or object.
     */
    static createFrom($$source: any = {}): GatewayMonitorRuntime {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GatewayMonitorRuntime($$parsedSource as Partial<GatewayMonitorRuntime>);
    }
}

export class GatewayMonitorTokens {
    "reserved": boolean;
    "input": number;
    "output": number;
    "cached": number;
    "total": number;

    /** Creates a new GatewayMonitorTokens instance. */
    constructor($$source: Partial<GatewayMonitorTokens> = {}) {
        if (!("reserved" in $$source)) {
            this["reserved"] = false;
        }
        if (!("input" in $$source)) {
            this["input"] = 0;
        }
        if (!("output" in $$source)) {
            this["output"] = 0;
        }
        if (!("cached" in $$source)) {
            this["cached"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GatewayMonitorTokens instance from a string or object.
     */
    static createFrom($$source: any = {}): GatewayMonitorTokens {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GatewayMonitorTokens($$parsedSource as Partial<GatewayMonitorTokens>);
    }
}

/**
 * GatewayQueueStats mirrors the queue_stats field.
 */
export class GatewayQueueStats {
    "queued": number;
    "running": number;

    /** Creates a new GatewayQueueStats instance. */
    constructor($$source: Partial<GatewayQueueStats> = {}) {
        if (!("queued" in $$source)) {
            this["queued"] = 0;
        }
        if (!("running" in $$source)) {
            this["running"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GatewayQueueStats instance from a string or object.
     */
    static createFrom($$source: any = {}): GatewayQueueStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GatewayQueueStats($$parsedSource as Partial<GatewayQueueStats>);
    }
}

/**
 * GatewaySession is the sessions* endpoint shape.
 */
export class GatewaySession {
    "session_id": string;

    /**
     * 首次提问后的会话名；空表示未命名
     */
    "name"?: string;
    "user"?: string;
    "sources": string[];
    "last_active"?: string;
    "last_active_nanos"?: number;
    "agent"?: GatewaySessionAgent | null;

    /** Creates a new GatewaySession instance. */
    constructor($$source: Partial<GatewaySession> = {}) {
        if (!("session_id" in $$source)) {
            this["session_id"] = "";
        }
        if (!("sources" in $$source)) {
            this["sources"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GatewaySession instance from a string or object.
     */
    static createFrom($$source: any = {}): GatewaySession {
        const $$createField3_0 = $$createType6;
        const $$createField6_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sources" in $$parsedSource) {
            $$parsedSource["sources"] = $$createField3_0($$parsedSource["sources"]);
        }
        if ("agent" in $$parsedSource) {
            $$parsedSource["agent"] = $$createField6_0($$parsedSource["agent"]);
        }
        return new GatewaySession($$parsedSource as Partial<GatewaySession>);
    }
}

/**
 * GatewaySessionAgent mirrors the per-session agent state embedded in the
 * unified session view.
 */
export class GatewaySessionAgent {
    "status": string;
    "task"?: GatewayTaskSnapshot | null;

    /** Creates a new GatewaySessionAgent instance. */
    constructor($$source: Partial<GatewaySessionAgent> = {}) {
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GatewaySessionAgent instance from a string or object.
     */
    static createFrom($$source: any = {}): GatewaySessionAgent {
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("task" in $$parsedSource) {
            $$parsedSource["task"] = $$createField1_0($$parsedSource["task"]);
        }
        return new GatewaySessionAgent($$parsedSource as Partial<GatewaySessionAgent>);
    }
}

/**
 * GatewaySessionsResponse mirrors GET /sessions.
 */
export class GatewaySessionsResponse {
    "user": string;
    "sessions": GatewaySession[];

    /** Creates a new GatewaySessionsResponse instance. */
    constructor($$source: Partial<GatewaySessionsResponse> = {}) {
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("sessions" in $$source)) {
            this["sessions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GatewaySessionsResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): GatewaySessionsResponse {
        const $$createField1_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sessions" in $$parsedSource) {
            $$parsedSource["sessions"] = $$createField1_0($$parsedSource["sessions"]);
        }
        return new GatewaySessionsResponse($$parsedSource as Partial<GatewaySessionsResponse>);
    }
}

/**
 * GatewaySnapshot mirrors read_cached_content responses (single file or a
 * source listing when a source matches multiple files).
 */
export class GatewaySnapshot {
    "path"?: string;
    "size"?: number;
    "returned"?: number;
    "truncated"?: boolean;
    "content"?: string;
    "source"?: string;
    "files"?: string[];

    /** Creates a new GatewaySnapshot instance. */
    constructor($$source: Partial<GatewaySnapshot> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GatewaySnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): GatewaySnapshot {
        const $$createField6_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField6_0($$parsedSource["files"]);
        }
        return new GatewaySnapshot($$parsedSource as Partial<GatewaySnapshot>);
    }
}

/**
 * GatewaySourceInfo is one entry of GET /sources.
 */
export class GatewaySourceInfo {
    "name": string;
    "files": string[];

    /** Creates a new GatewaySourceInfo instance. */
    constructor($$source: Partial<GatewaySourceInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("files" in $$source)) {
            this["files"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GatewaySourceInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): GatewaySourceInfo {
        const $$createField1_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField1_0($$parsedSource["files"]);
        }
        return new GatewaySourceInfo($$parsedSource as Partial<GatewaySourceInfo>);
    }
}

/**
 * GatewayTaskSnapshot mirrors the task object returned by the agent endpoints.
 */
export class GatewayTaskSnapshot {
    "id": string;
    "user"?: string;
    "session"?: string;
    "status": string;
    "workspace"?: string;
    "log_dir"?: string;
    "raw_log_path"?: string;
    "started_at"?: string;
    "ended_at"?: string;
    "exit_code"?: number | null;
    "error"?: string;

    /** Creates a new GatewayTaskSnapshot instance. */
    constructor($$source: Partial<GatewayTaskSnapshot> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GatewayTaskSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): GatewayTaskSnapshot {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GatewayTaskSnapshot($$parsedSource as Partial<GatewayTaskSnapshot>);
    }
}

/**
 * ProxyRequest is a generic HTTP request forwarded to the ScienceFlow gateway.
 */
export class ProxyRequest {
    "method": string;
    "path": string;
    "body"?: string;
    "headers"?: { [_ in string]?: string };

    /** Creates a new ProxyRequest instance. */
    constructor($$source: Partial<ProxyRequest> = {}) {
        if (!("method" in $$source)) {
            this["method"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProxyRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ProxyRequest {
        const $$createField3_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField3_0($$parsedSource["headers"]);
        }
        return new ProxyRequest($$parsedSource as Partial<ProxyRequest>);
    }
}

/**
 * ProxyResponse is the generic HTTP response returned to the frontend.
 */
export class ProxyResponse {
    "status": number;
    "body": string;
    "etag"?: string;
    "notModified"?: boolean;
    "transport"?: TransportMeta | null;

    /** Creates a new ProxyResponse instance. */
    constructor($$source: Partial<ProxyResponse> = {}) {
        if (!("status" in $$source)) {
            this["status"] = 0;
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProxyResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): ProxyResponse {
        const $$createField4_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("transport" in $$parsedSource) {
            $$parsedSource["transport"] = $$createField4_0($$parsedSource["transport"]);
        }
        return new ProxyResponse($$parsedSource as Partial<ProxyResponse>);
    }
}

/**
 * SystemStats carries live resource usage of the local machine running the
 * desktop app: overall CPU load, memory usage, and storage of the Windows
 * system drive (normally C:\).
 */
export class SystemStats {
    "cpu_percent": number;
    "memory_used_bytes": number;
    "memory_total_bytes": number;
    "memory_percent": number;
    "disk_used_bytes": number;
    "disk_total_bytes": number;
    "disk_percent": number;
    "disk_path": string;

    /** Creates a new SystemStats instance. */
    constructor($$source: Partial<SystemStats> = {}) {
        if (!("cpu_percent" in $$source)) {
            this["cpu_percent"] = 0;
        }
        if (!("memory_used_bytes" in $$source)) {
            this["memory_used_bytes"] = 0;
        }
        if (!("memory_total_bytes" in $$source)) {
            this["memory_total_bytes"] = 0;
        }
        if (!("memory_percent" in $$source)) {
            this["memory_percent"] = 0;
        }
        if (!("disk_used_bytes" in $$source)) {
            this["disk_used_bytes"] = 0;
        }
        if (!("disk_total_bytes" in $$source)) {
            this["disk_total_bytes"] = 0;
        }
        if (!("disk_percent" in $$source)) {
            this["disk_percent"] = 0;
        }
        if (!("disk_path" in $$source)) {
            this["disk_path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SystemStats instance from a string or object.
     */
    static createFrom($$source: any = {}): SystemStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SystemStats($$parsedSource as Partial<SystemStats>);
    }
}

/**
 * TransportMeta mirrors the X-SF-Transport-* headers sent by the backend.
 */
export class TransportMeta {
    "mode"?: string;
    "cache"?: string;
    "build_ms"?: number;
    "response_ms"?: number;
    "payload_bytes"?: number;
    "modules_count"?: number;

    /** Creates a new TransportMeta instance. */
    constructor($$source: Partial<TransportMeta> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TransportMeta instance from a string or object.
     */
    static createFrom($$source: any = {}): TransportMeta {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TransportMeta($$parsedSource as Partial<TransportMeta>);
    }
}

/**
 * UploadResult mirrors the backend's dataset upload response.
 */
export class UploadResult {
    "path": string;
    "name": string;

    /** Creates a new UploadResult instance. */
    constructor($$source: Partial<UploadResult> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UploadResult instance from a string or object.
     */
    static createFrom($$source: any = {}): UploadResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UploadResult($$parsedSource as Partial<UploadResult>);
    }
}

/**
 * UploadedFile is a single file payload (base64-encoded) for dataset upload.
 */
export class UploadedFile {
    "filename": string;
    "data": string;

    /** Creates a new UploadedFile instance. */
    constructor($$source: Partial<UploadedFile> = {}) {
        if (!("filename" in $$source)) {
            this["filename"] = "";
        }
        if (!("data" in $$source)) {
            this["data"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UploadedFile instance from a string or object.
     */
    static createFrom($$source: any = {}): UploadedFile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UploadedFile($$parsedSource as Partial<UploadedFile>);
    }
}

/**
 * WorkspaceDirUploadResult mirrors the gateway's directory upload response.
 */
export class WorkspaceDirUploadResult {
    "root": string;
    "extracted": number;
    "total_bytes": number;
    "skipped_symlinks": number;

    /** Creates a new WorkspaceDirUploadResult instance. */
    constructor($$source: Partial<WorkspaceDirUploadResult> = {}) {
        if (!("root" in $$source)) {
            this["root"] = "";
        }
        if (!("extracted" in $$source)) {
            this["extracted"] = 0;
        }
        if (!("total_bytes" in $$source)) {
            this["total_bytes"] = 0;
        }
        if (!("skipped_symlinks" in $$source)) {
            this["skipped_symlinks"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceDirUploadResult instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceDirUploadResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkspaceDirUploadResult($$parsedSource as Partial<WorkspaceDirUploadResult>);
    }
}

export class WorkspaceUploadItem {
    "path": string;
    "size": number;

    /** Creates a new WorkspaceUploadItem instance. */
    constructor($$source: Partial<WorkspaceUploadItem> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceUploadItem instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceUploadItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkspaceUploadItem($$parsedSource as Partial<WorkspaceUploadItem>);
    }
}

/**
 * WorkspaceUploadResult mirrors the gateway's file upload response.
 */
export class WorkspaceUploadResult {
    "root": string;
    "uploaded": WorkspaceUploadItem[];

    /** Creates a new WorkspaceUploadResult instance. */
    constructor($$source: Partial<WorkspaceUploadResult> = {}) {
        if (!("root" in $$source)) {
            this["root"] = "";
        }
        if (!("uploaded" in $$source)) {
            this["uploaded"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceUploadResult instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceUploadResult {
        const $$createField1_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("uploaded" in $$parsedSource) {
            $$parsedSource["uploaded"] = $$createField1_0($$parsedSource["uploaded"]);
        }
        return new WorkspaceUploadResult($$parsedSource as Partial<WorkspaceUploadResult>);
    }
}

// Private type creation functions
const $$createType0 = FileTreeNode.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = GatewayTaskSnapshot.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = GatewayQueueStats.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($Create.Any);
const $$createType7 = GatewayMonitorResource.createFrom;
const $$createType8 = GatewayMonitorTokens.createFrom;
const $$createType9 = GatewayMonitorRuntime.createFrom;
const $$createType10 = GatewaySessionAgent.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = GatewaySession.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = $Create.Map($Create.Any, $Create.Any);
const $$createType15 = TransportMeta.createFrom;
const $$createType16 = $Create.Nullable($$createType15);
const $$createType17 = WorkspaceUploadItem.createFrom;
const $$createType18 = $Create.Array($$createType17);
